-- ==============================================================================
-- SIGAE - ESQUEMA COMPLETO Y CORREGIDO PARA EL NUEVO PROYECTO SUPABASE
-- Ordenado con dependencias de Foreign Keys y extensiones UUID garantizadas
-- ==============================================================================

-- 1. EXTENSIONES REQUERIDAS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABLAS BASE E INDEPENDIENTES (SIN CLAVES FORÁNEAS EXTERNAS)
CREATE TABLE IF NOT EXISTS public.perfil_escuela (
  id_escuela text NOT NULL,
  nombre_institucion text,
  codigo_dea text,
  rif text,
  direccion text,
  mision text,
  vision text,
  objetivo text,
  peic text,
  CONSTRAINT perfil_escuela_pkey PRIMARY KEY (id_escuela)
);

CREATE TABLE IF NOT EXISTS public.conf_preguntas_seguridad (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pregunta character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conf_preguntas_seguridad_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL UNIQUE,
  permisos jsonb DEFAULT '{}'::jsonb,
  idx bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_escuela text DEFAULT 'global'::text,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.conf_periodos (
  id_parametro text NOT NULL,
  valor text NOT NULL,
  fecha_inicio text,
  fecha_fin text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conf_periodos_pkey PRIMARY KEY (id_parametro)
);

CREATE TABLE IF NOT EXISTS public.conf_lapsos (
  id_parametro text NOT NULL,
  valor text NOT NULL,
  fecha_inicio text,
  fecha_fin text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conf_lapsos_pkey PRIMARY KEY (id_parametro)
);

CREATE TABLE IF NOT EXISTS public.conf_niveles (
  id_parametro text NOT NULL,
  valor text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conf_niveles_pkey PRIMARY KEY (id_parametro)
);

CREATE TABLE IF NOT EXISTS public.conf_grados (
  id_parametro text NOT NULL,
  valor text NOT NULL UNIQUE,
  orden integer DEFAULT 0,
  CONSTRAINT conf_grados_pkey PRIMARY KEY (id_parametro)
);

CREATE TABLE IF NOT EXISTS public.conf_secciones (
  id_parametro text NOT NULL,
  valor text NOT NULL UNIQUE,
  CONSTRAINT conf_secciones_pkey PRIMARY KEY (id_parametro)
);

CREATE TABLE IF NOT EXISTS public.espacios (
  id text NOT NULL,
  nombre text NOT NULL,
  tipo text NOT NULL,
  capacidad integer DEFAULT 0,
  id_escuela text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT espacios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.diccionarios_empresa (
  id_parametro text NOT NULL,
  categoria text NOT NULL,
  valor text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT diccionarios_empresa_pkey PRIMARY KEY (id_parametro)
);

CREATE TABLE IF NOT EXISTS public.div_pol_vzla (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  estado text NOT NULL,
  municipio text NOT NULL,
  parroquia text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT div_pol_vzla_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.catalogo_formaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  categoria text NOT NULL,
  titulo text NOT NULL,
  descripcion text,
  duracion text,
  nivel text DEFAULT 'Básico'::text,
  imagen_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT catalogo_formaciones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sigma_conocimiento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tema text NOT NULL,
  palabras_clave text[] NOT NULL,
  respuesta text NOT NULL,
  accion_tipo text,
  accion_valor text,
  roles_permitidos text[] DEFAULT '{}'::text[],
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT sigma_conocimiento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sigma_preguntas_pendientes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pregunta text NOT NULL,
  estado text DEFAULT 'pendiente'::text,
  fecha timestamp with time zone DEFAULT now(),
  CONSTRAINT sigma_preguntas_pendientes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cargos (
  id_cargo text NOT NULL,
  nombre_cargo text NOT NULL,
  tipo_cargo text NOT NULL,
  descripcion text,
  depende_de text,
  id_escuela character varying,
  CONSTRAINT cargos_pkey PRIMARY KEY (id_cargo)
);

CREATE TABLE IF NOT EXISTS public.ajustes_globales (
  clave character varying NOT NULL,
  valor text NOT NULL,
  descripcion text,
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT ajustes_globales_pkey PRIMARY KEY (clave)
);

CREATE TABLE IF NOT EXISTS public.notificaciones (
  id_notificacion uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_destino text NOT NULL,
  titulo text NOT NULL,
  mensaje text NOT NULL,
  leida boolean DEFAULT false,
  tipo text DEFAULT 'info'::text,
  created_at timestamp with time zone DEFAULT now(),
  leido boolean DEFAULT false,
  CONSTRAINT notificaciones_pkey PRIMARY KEY (id_notificacion)
);

CREATE TABLE IF NOT EXISTS public.historial_auditoria (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  fecha timestamp with time zone DEFAULT now(),
  usuario_cedula text NOT NULL,
  usuario_nombre text NOT NULL,
  escuela text NOT NULL,
  modulo text NOT NULL,
  accion text NOT NULL,
  detalles text,
  CONSTRAINT historial_auditoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.invitados (
  id_invitado uuid NOT NULL DEFAULT gen_random_uuid(),
  cedula character varying NOT NULL,
  nombres character varying NOT NULL,
  apellidos character varying NOT NULL,
  correo character varying,
  telefono character varying NOT NULL,
  razon_visita text NOT NULL,
  escuela_id character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invitados_pkey PRIMARY KEY (id_invitado)
);

-- 3. USUARIOS Y ESTUDIANTES
CREATE TABLE IF NOT EXISTS public.usuarios (
  id_usuario uuid NOT NULL DEFAULT gen_random_uuid(),
  cedula character varying NOT NULL UNIQUE,
  nombre_completo character varying NOT NULL,
  email character varying,
  telefono character varying,
  rol character varying DEFAULT 'Docente'::character varying,
  cargo character varying,
  clave character varying,
  primer_ingreso boolean DEFAULT true,
  estado character varying DEFAULT 'Activo'::character varying,
  intentos_fallidos integer DEFAULT 0,
  bloqueo_hasta timestamp with time zone,
  solicito_reseteo boolean DEFAULT false,
  preguntas_seguridad jsonb,
  perfil_acceso jsonb DEFAULT '{"instituciones": []}'::jsonb,
  fecha_ult_clave timestamp with time zone DEFAULT now(),
  id_escuela text DEFAULT 'sb'::text,
  credencial_biometrica text,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.solicitud_cupos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo_escuela character varying NOT NULL,
  codigo_unico character varying UNIQUE,
  acepta_terminos boolean NOT NULL DEFAULT false,
  estudiante_nombres character varying NOT NULL,
  estudiante_apellidos character varying NOT NULL,
  estudiante_cedula character varying,
  estudiante_fecha_nacimiento date NOT NULL,
  estudiante_sexo character varying NOT NULL,
  estudiante_orden_nacimiento character varying,
  estudiante_condicion_neuro character varying DEFAULT 'Neurotípico'::character varying,
  estudiante_tipo_condicion character varying,
  estudiante_informe_neuro boolean DEFAULT false,
  estudiante_certificado_conapdis boolean DEFAULT false,
  estudiante_condicion_medica text DEFAULT 'Ninguna'::text,
  estudiante_alergico_medicamentos text DEFAULT 'Ninguna'::text,
  grado_solicitado character varying NOT NULL,
  parentesco character varying NOT NULL,
  plantel_procedencia character varying,
  direccion_habitacion text,
  estado_habitacion character varying,
  municipio_habitacion character varying,
  parroquia_habitacion character varying,
  tiene_otros_inscritos boolean DEFAULT false,
  representante_nombres character varying NOT NULL,
  representante_apellidos character varying NOT NULL,
  representante_cedula character varying NOT NULL,
  representante_telefono character varying NOT NULL,
  representante_telefono2 character varying,
  representante_email character varying NOT NULL,
  representante_parentesco character varying NOT NULL,
  representante_trabaja_pdvsa character varying NOT NULL DEFAULT 'No'::character varying,
  pdvsa_condicion_laboral character varying,
  pdvsa_tipo_nomina character varying,
  pdvsa_negocio_filial character varying,
  pdvsa_gerencia character varying,
  pdvsa_email_empresa character varying,
  pdvsa_localidad_trabajo character varying,
  madre_cedula character varying,
  madre_email character varying,
  madre_trabaja_pdvsa boolean DEFAULT false,
  requiere_transporte boolean DEFAULT false,
  ruta_transporte character varying,
  doc_ficha text,
  doc_foto_estudiante text,
  doc_partida_nacimiento text,
  doc_cedula_estudiante text,
  doc_partida_trabajador text,
  doc_partida_nexo text,
  estado character varying NOT NULL DEFAULT 'Pendiente'::character varying,
  observaciones text,
  creado_por character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  estudiante_con_quien_vive text,
  madre_vive text DEFAULT 'Sí'::text,
  madre_es_representante boolean DEFAULT false,
  madre_nombres text,
  madre_apellidos text,
  madre_fecha_nacimiento text,
  madre_telefono text,
  padre_vive text DEFAULT 'Sí'::text,
  padre_es_representante boolean DEFAULT false,
  padre_nombres text,
  padre_apellidos text,
  padre_cedula text,
  padre_fecha_nacimiento text,
  padre_email text,
  padre_telefono text,
  padre_trabaja_pdvsa boolean DEFAULT false,
  estudiante_reconocido_por_padre text DEFAULT 'Sí'::text,
  CONSTRAINT solicitud_cupos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estudiantes_vinculaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo_escuela text NOT NULL CHECK (codigo_escuela = ANY (ARRAY['sb'::text, 'lb'::text])),
  cedula_representante text NOT NULL,
  nombres_representante text NOT NULL,
  apellidos_representante text NOT NULL,
  cedula_estudiante text NOT NULL UNIQUE,
  nombres_estudiante text NOT NULL,
  apellidos_estudiante text NOT NULL,
  grado_actual text DEFAULT 'Sin Grado Asignado'::text,
  seccion_actual text DEFAULT 'A'::text,
  estado text DEFAULT 'Activo'::text CHECK (estado = ANY (ARRAY['Activo'::text, 'Inactivo'::text])),
  creado_por text,
  datos_actualizados jsonb DEFAULT '{}'::jsonb,
  fecha_ultima_actualizacion timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT estudiantes_vinculaciones_pkey PRIMARY KEY (id)
);

-- 4. ENCUESTAS
CREATE TABLE IF NOT EXISTS public.encuestas (
  id text NOT NULL,
  titulo text NOT NULL,
  descripcion text,
  codigo_escuela text DEFAULT 'ambas'::text,
  roles_permitidos jsonb DEFAULT '[]'::jsonb,
  estado text DEFAULT 'Borrador'::text,
  es_obligatoria boolean DEFAULT false,
  es_anonima boolean DEFAULT false,
  permitir_multiples_respuestas boolean DEFAULT false,
  fecha_inicio text,
  fecha_fin text,
  preguntas jsonb DEFAULT '[]'::jsonb,
  creado_por text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT encuestas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.encuestas_respuestas (
  id text NOT NULL,
  encuesta_id text,
  usuario_cedula text,
  usuario_nombre text,
  usuario_rol text,
  codigo_escuela text,
  respuestas jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT encuestas_respuestas_pkey PRIMARY KEY (id),
  CONSTRAINT encuestas_respuestas_encuesta_id_fkey FOREIGN KEY (encuesta_id) REFERENCES public.encuestas(id) ON DELETE CASCADE
);

-- 5. TRANSPORTE ESCOLAR
CREATE TABLE IF NOT EXISTS public.transporte_rutas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  escuela_codigo text NOT NULL CHECK (escuela_codigo = ANY (ARRAY['sb'::text, 'lb'::text])),
  nombre text NOT NULL,
  sectores text,
  chofer_nombre text,
  chofer_telefono text,
  unidad_placa text,
  unidad_modelo text,
  paradas_json jsonb DEFAULT '[]'::jsonb,
  docente_id uuid,
  validez_desde date,
  validez_hasta date,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  activo boolean DEFAULT true,
  CONSTRAINT transporte_rutas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transporte_paradas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  escuela_codigo text CHECK (escuela_codigo = ANY (ARRAY['sb'::text, 'lb'::text])),
  nombre_parada text NOT NULL,
  descripcion text,
  orden integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT transporte_paradas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transporte_operaciones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ruta_id uuid NOT NULL,
  escuela_codigo text NOT NULL CHECK (escuela_codigo = ANY (ARRAY['sb'::text, 'lb'::text])),
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  sentido text NOT NULL CHECK (sentido = ANY (ARRAY['Casa - Escuela'::text, 'Escuela - Casa'::text])),
  estado text NOT NULL CHECK (estado = ANY (ARRAY['Programada'::text, 'En Ruta'::text, 'Finalizada'::text])),
  ubicacion_actual text,
  ultima_actualizacion timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  historial_paradas jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT transporte_operaciones_pkey PRIMARY KEY (id),
  CONSTRAINT transporte_operaciones_ruta_id_fkey FOREIGN KEY (ruta_id) REFERENCES public.transporte_rutas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.transporte_asignaciones (
  id_asignacion uuid NOT NULL DEFAULT gen_random_uuid(),
  id_ruta character varying,
  id_parada character varying,
  estudiante_cedula character varying NOT NULL,
  nombre_estudiante character varying NOT NULL,
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT transporte_asignaciones_pkey PRIMARY KEY (id_asignacion)
);

CREATE TABLE IF NOT EXISTS public.transporte_viajes_activos (
  id_viaje character varying NOT NULL,
  id_ruta character varying,
  estado character varying DEFAULT 'No Iniciado'::character varying,
  parada_actual_id character varying,
  pasajeros_a_bordo integer DEFAULT 0,
  iniciado_por character varying NOT NULL,
  iniciado_en timestamp with time zone,
  actualizado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT transporte_viajes_activos_pkey PRIMARY KEY (id_viaje)
);

CREATE TABLE IF NOT EXISTS public.notificaciones_globales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escuela_codigo text NOT NULL,
  ruta_id uuid,
  titulo text NOT NULL,
  cuerpo text NOT NULL,
  tipo text DEFAULT 'transporte'::text,
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT notificaciones_globales_pkey PRIMARY KEY (id)
);

-- 6. SALONES Y COLECTIVOS
CREATE TABLE IF NOT EXISTS public.salones (
  id_salon text NOT NULL,
  id_escuela text NOT NULL,
  nivel_educativo text NOT NULL,
  grado_anio text NOT NULL,
  seccion text NOT NULL,
  nombre_salon text NOT NULL,
  estatus text DEFAULT 'Activo'::text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  id_espacio text,
  docentes_guias character varying(20)[] DEFAULT ARRAY[]::character varying(20)[],
  CONSTRAINT salones_pkey PRIMARY KEY (id_salon),
  CONSTRAINT salones_id_espacio_fkey FOREIGN KEY (id_espacio) REFERENCES public.espacios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.colectivos (
  id_colectivo character varying NOT NULL,
  nombre_colectivo character varying NOT NULL,
  descripcion text,
  id_escuela character varying NOT NULL,
  vocero_cedula character varying NOT NULL,
  vocero_nombre character varying NOT NULL,
  integrantes jsonb NOT NULL DEFAULT '[]'::jsonb,
  planificacion_anual jsonb NOT NULL DEFAULT '[]'::jsonb,
  reportes_gestion jsonb NOT NULL DEFAULT '[]'::jsonb,
  creado_en timestamp with time zone DEFAULT now(),
  CONSTRAINT colectivos_pkey PRIMARY KEY (id_colectivo),
  CONSTRAINT colectivos_id_escuela_fkey FOREIGN KEY (id_escuela) REFERENCES public.perfil_escuela(id_escuela) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.expedientes_docentes (
  usuario_cedula character varying NOT NULL,
  sexo character varying NOT NULL,
  fecha_nacimiento date NOT NULL,
  estado_civil character varying NOT NULL,
  direccion text NOT NULL,
  titulo_obtenido character varying NOT NULL,
  nivel_instruccion character varying NOT NULL,
  universidad character varying NOT NULL,
  anio_egreso integer NOT NULL,
  fecha_ingreso date,
  tipo_nomina character varying,
  carga_horaria integer,
  estatus_laboral character varying,
  documentos jsonb NOT NULL DEFAULT '{"cv": false, "cedula": false, "titulo": false, "constancia": false}'::jsonb,
  datos_salud jsonb DEFAULT '{}'::jsonb,
  datos_electoral jsonb DEFAULT '{}'::jsonb,
  datos_vivienda jsonb DEFAULT '{}'::jsonb,
  carga_familiar jsonb DEFAULT '[]'::jsonb,
  cursos_realizados jsonb DEFAULT '[]'::jsonb,
  plan_formacion jsonb DEFAULT '[]'::jsonb,
  necesidades_extra text,
  creado_en timestamp with time zone DEFAULT now(),
  actualizado_en timestamp with time zone DEFAULT now(),
  n_personal character varying,
  grupo character varying,
  gerencia character varying,
  organizacion_proceso character varying,
  experiencia_externa jsonb DEFAULT '[]'::jsonb,
  historico_pdvsa jsonb DEFAULT '[]'::jsonb,
  acciones_personal jsonb DEFAULT '{"salario": [], "promocion": [], "evaluacion": []}'::jsonb,
  otros_idiomas text,
  destrezas_habilidades text,
  desarrollo_carrera text,
  observaciones_ficha text,
  fecha_aniversaria date,
  periodo_vacacional character varying,
  vacaciones_desde date,
  vacaciones_hasta date,
  dias_habiles integer,
  dias_continuos integer,
  fecha_retorno date,
  estudios_superiores jsonb DEFAULT '[]'::jsonb,
  cargo_actual character varying,
  indicador character varying,
  supervisor_nombre character varying,
  supervisor_cedula character varying,
  supervisor_telefono character varying,
  CONSTRAINT expedientes_docentes_pkey PRIMARY KEY (usuario_cedula),
  CONSTRAINT expedientes_docentes_usuario_cedula_fkey FOREIGN KEY (usuario_cedula) REFERENCES public.usuarios(cedula) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.certificados_modelos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  nombre_borrador text,
  titulo text,
  actividad text,
  cuerpo text,
  horas_academicas integer,
  fecha_certificada date,
  formato_papel text,
  tema_color text,
  fuente_estilo text,
  plantilla_diseno text,
  firmantes jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT certificados_modelos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.certificados_emitidos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  codigo_verificacion text NOT NULL UNIQUE,
  modelo_id uuid,
  receptor_cedula text,
  receptor_nombre text NOT NULL,
  estado text DEFAULT 'valido'::text,
  CONSTRAINT certificados_emitidos_pkey PRIMARY KEY (id),
  CONSTRAINT certificados_emitidos_modelo_id_fkey FOREIGN KEY (modelo_id) REFERENCES public.certificados_modelos(id) ON DELETE CASCADE
);
