plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Luis Velásquez\\Desktop\\SIGAE_Unificado\\SIGAE_V1\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Luis Velásquez\\Desktop\\SIGAE_Unificado\\SIGAE_V1"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]