CREATE TABLE actualizaciones_datos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    codigo_unico TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Estudiante
    estudiante_nombres TEXT,
    estudiante_apellidos TEXT,
    estudiante_cedula TEXT,
    estudiante_fecha_nacimiento DATE,
    estudiante_pais_nacimiento TEXT,
    estudiante_pais_nacimiento_otro TEXT,
    estudiante_lugar_nacimiento TEXT,
    estudiante_municipio_nacimiento TEXT,
    estudiante_estado_nacimiento TEXT,
    estudiante_folio_nacimiento TEXT,
    estudiante_acta_nacimiento TEXT,
    estudiante_fecha_acta_nacimiento DATE,
    estudiante_sexo TEXT,
    estudiante_condicion_neuro TEXT,
    estudiante_tipo_condicion TEXT,
    estudiante_tipo_condicion_otro TEXT,
    estudiante_informe_neuro BOOLEAN,
    estudiante_certificado_conapdis BOOLEAN,
    estudiante_grupo_sanguineo TEXT,
    estudiante_condicion_medica TEXT,
    estudiante_condicion_medica_otro TEXT,
    estudiante_alergico_medicamentos TEXT,
    estudiante_alergico_medicamentos_otro TEXT,
    estudiante_tiene_alergia_medicamentos TEXT,
    estudiante_tiene_alergia_alimentos TEXT,
    estudiante_alergia_alimentos TEXT,
    estudiante_alergia_alimentos_otro TEXT,
    estudiante_tiene_otras_alergias TEXT,
    estudiante_otras_alergias TEXT,
    estudiante_otras_alergias_otro TEXT,
    grado_solicitado TEXT,
    parentesco TEXT,
    estudiante_con_quien_vive JSONB,
    estudiante_con_quien_vive_otro TEXT,
    estudiante_reconocido_por_padre TEXT,

    -- Dirección
    estado_habitacion TEXT,
    municipio_habitacion TEXT,
    parroquia_habitacion TEXT,
    direccion_habitacion TEXT,

    -- Otros
    tiene_otros_inscritos BOOLEAN,
    plantel_procedencia TEXT,

    -- Ruta Escolar
    requiere_transporte BOOLEAN,
    ruta_transporte TEXT,
    parada_transporte TEXT,

    -- Antropometricos
    talla_franela TEXT,
    talla_pantalon TEXT,
    talla_calzado TEXT,
    estatura_metros TEXT,
    peso_kg TEXT,

    -- Documentos fotográficos
    foto_carnet_url TEXT,
    foto_cedula_estudiante_url TEXT,
    foto_partida_nacimiento_url TEXT,
    foto_cedula_madre_url TEXT,
    foto_cedula_padre_url TEXT,

    -- Habilidades
    tiene_habilidad_cultura TEXT,
    habilidad_cultura_instrumento TEXT,
    habilidad_cultura_instrumento_otro TEXT,
    habilidad_cultura_orquesta TEXT,
    constancia_cultura_url TEXT,
    tiene_habilidad_danza TEXT,
    habilidad_danza_tipo TEXT,
    habilidad_danza_academia TEXT,
    constancia_danza_url TEXT,
    tiene_habilidad_deporte TEXT,
    habilidad_deporte_disciplina TEXT,
    habilidad_deporte_disciplina_otro TEXT,
    habilidad_deporte_academia TEXT,
    constancia_deporte_url TEXT,

    -- Tecnologicos
    posee_computadora TEXT,
    posee_internet TEXT,
    posee_celular TEXT,

    -- Representante
    representante_nombres TEXT,
    representante_apellidos TEXT,
    representante_cedula TEXT,
    representante_fecha_nacimiento DATE,
    representante_telefono TEXT,
    representante_telefono2 TEXT,
    representante_email TEXT,
    representante_parentesco TEXT,
    representante_direccion TEXT,
    representante_trabaja_pdvsa TEXT,

    -- Madre
    madre_vive TEXT,
    madre_es_representante BOOLEAN,
    madre_nombres TEXT,
    madre_apellidos TEXT,
    madre_cedula TEXT,
    madre_fecha_nacimiento DATE,
    madre_lugar_nacimiento TEXT,
    madre_localidad_trabajo TEXT,
    madre_email TEXT,
    madre_telefono TEXT,
    madre_direccion TEXT,
    madre_trabaja_pdvsa BOOLEAN,
    madre_formacion_hidrocarburos TEXT,
    madre_componente_docente TEXT,

    -- Padre
    padre_vive TEXT,
    padre_es_representante BOOLEAN,
    padre_reconoce TEXT,
    padre_nombres TEXT,
    padre_apellidos TEXT,
    padre_cedula TEXT,
    padre_fecha_nacimiento DATE,
    padre_lugar_nacimiento TEXT,
    padre_email TEXT,
    padre_telefono TEXT,
    padre_direccion TEXT,
    padre_trabaja_pdvsa BOOLEAN,
    padre_formacion_hidrocarburos TEXT,
    padre_componente_docente TEXT,

    -- PDVSA
    pdvsa_condicion_laboral TEXT,
    pdvsa_tipo_nomina TEXT,
    pdvsa_negocio_filial TEXT,
    pdvsa_gerencia TEXT,
    pdvsa_email_empresa TEXT,
    pdvsa_localidad_trabajo TEXT,
    pdvsa_localidad_trabajo_otra TEXT
);
